version: '3.7'

name: codeflix_mysql

services:
  mysql:
    container_name: codeflix_adm_videos_mysql
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: sql459037
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - codeflix_mysql01:/var/lib/mysql
    networks:
      - codeflix_mysql
    profiles: ["mysql", "all"]

networks:
  codeflix_mysql:
    external: true

volumes:
  codeflix_mysql01:
    external: true